version: "3.8"

services:
  bot:
    build:
      context: .
    container_name: aiogram_bot
    command: sh -c "python3 -m bot.main"
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - realogica_network
    network_mode: host

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - realogica_network

networks:
  realogica_network:
    driver: bridge

volumes:
    redis_data:


