from emoji import emojize

BUTTONS = {
    'REFERAL': emojize(':man_technologist: Реферальная программа'),
    'EDUCATION': emojize(':graduation_cap: Обучение'),
    'QUIZ': emojize(':books: Тестирование'),
    'HELP': emojize(':open_mailbox_with_raised_flag: Написать в поддержку'),
    'MENU': emojize(':left_arrow: В главное меню'),
    'START_QUIZ': emojize(':play_button: Начать тестирование'),
    'RESULTS_QUIZ': emojize(':open_book: Посмотреть свои ответы'),
    'BACK': emojize(':reverse_button: К списку уроков'),
    'START_TASK': emojize(':check_mark_button: Выполнить задание'),
    'CLOSE_LESSON': emojize(':play_button: Следующий урок'),
    'NEXT': emojize(':play_button: Следующая'),
    'PREVIOUS': emojize(':reverse_button: Предыдущая'),
    'AGAIN': emojize(':repeat_button: Пройти урок заново'),
    'SKIP': emojize(':yellow_square: Пропустить'),
    'DONE': emojize(':green_square: Сделал'),
    'BALANCE': emojize(':money_bag: Баланс'),
    'PROMOCODES': emojize(':admission_tickets: Промокоды'),
    'SEE_PROMOCODES': emojize(':open_book: Все промокоды'),
    'GENERATE_PROMOCODE': emojize(':plus: Сгенерировать промокод'),
    'GET_CERTIFICATE': emojize(':sparkle: Получить сертификат'),
    'KNOWLEDGE_BASE': emojize(':floppy_disk: База знаний'),
    'BACK_BASE': emojize(':left_arrow: Назад'),
    'TEST_EDUCATION': emojize(':open_book: Обучение'),
    'TEST_QUIZ': emojize(':bookmark_tabs: Начать тестирование'),
    'OWNER_QUIZ': emojize(':books: Все тестирования'),
    'OWNER_EDUCATION': emojize(':graduation_cap: Все курсы'),
}
